/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;
import java.util.Random;

public class App {
    public static void main(String[] args) {

        // 1. Lâmpada -----------------------------------------------------------
        System.out.println("1. Lâmpada -------------------------------------");
        Lampada lampada1 = new Lampada();
        Lampada lampada2 = new Lampada(true);

        String estadoLampada1 = lampada1.verEstado() ? "ligada" : "desligada";
        String estadoLampada2 = lampada2.verEstado() ? "ligada" : "desligada";

        System.out.println("Lampada 1: " + estadoLampada1);
        System.out.println("Lampada 2: " + estadoLampada2);

        lampada1.ligar();
        lampada2.desligar();

        estadoLampada1 = lampada1.verEstado() ? "ligada" : "desligada";
        estadoLampada2 = lampada2.verEstado() ? "ligada" : "desligada";

        System.out.println("Lampada 1: " + estadoLampada1);
        System.out.println("Lampada 2: " + estadoLampada2);
        System.out.println("Total de lâmpadas: " + Lampada.getContagem());
        System.out.println("\n");

        // 2. Pessoa -----------------------------------------------------------
        System.out.println("2. Pessoa -------------------------------------");
        Pessoa p1 = new Pessoa("11122233344");
        Pessoa p2 = new Pessoa("Maria", "");
        Pessoa p3 = new Pessoa("Jane", 26,"00012345600");

        p2.felizAniversario();
        p2.felizAniversario();
        p2.felizAniversario();

        boolean resultado_pessoa = p1.setIdade(-44);
        System.out.println("p1.setIdade(-44): " + resultado_pessoa);
        resultado_pessoa = p2.setNome("");
        System.out.println("p1.setNome(\"\"): " + resultado_pessoa);

        System.out.println(p1.getNome() + " tem " + p1.getIdade() + " anos e CPF " + p1.getCPF());
        System.out.println(p2.getNome() + " tem " + p2.getIdade() + " anos e CPF " + p2.getCPF());
        System.out.println(p3.getNome() + " tem " + p3.getIdade() + " anos e CPF " + p3.getCPF());
        System.out.println("\n");

        // 3. Retângulo -----------------------------------------------------------
        System.out.println("3. Retângulo -------------------------------------");
        Retangulo[] retangulos = new Retangulo[10];
        Random r = new Random();
        float maior = 0;

        for (int i = 0; i < 10; i++) {
            retangulos[i] = new Retangulo(r.nextInt(1,20), r.nextInt(1, 20));
        }

        System.out.println("O retângulo de maior área é " + Retangulo.getRetanguloMaiorArea());
        System.out.println("A maior área: " + Retangulo.getRetanguloMaiorArea().getArea());
        System.out.println("O retângulo de menor perímetro é " + Retangulo.getRetanguloMenorPerimetro());
        System.out.println("O menor perímetro: " + Retangulo.getRetanguloMenorPerimetro().getPerimetro());
        System.out.println("\n");

        // 4. Relógio -----------------------------------------------------------
        System.out.println("4. Relógio -------------------------------------");

        // Laboratório 1
        Relogio relogio1 = new Relogio((byte) 13);
        relogio1.ajustarHora((byte) 14, (byte) 58, (byte) 32);
        relogio1.avancaMinuto();
        relogio1.avancaMinuto();
        System.out.println(relogio1.getHorario());
        relogio1.ajustarHora((byte) 23, (byte) 59, (byte) 59);
        relogio1.avancaSegundo();
        System.out.println(relogio1.getHorario());
        relogio1.setAmpm(true);
        relogio1.ajustarHora((byte) 23, (byte) 30, (byte) 45);
        System.out.println(relogio1.getHorario());

        // Laboratório 2
        relogio1.setAmpm(false);
        Relogio relogio2 = new Relogio((byte) 0, (byte) 0, (byte) 0);
        System.out.println("Relório 2: " + relogio2.getHorario());
        relogio2.sync(relogio1);
        System.out.println("Relório 1: " + relogio1.getHorario());
        System.out.println("Relório 2: " + relogio2.getHorario());
        relogio1.avancaHora();
        relogio2.avancaHora();
        relogio2.avancaMinuto();
        relogio2.avancaSegundo();
        System.out.println("Relório 1: " + relogio1.getHorario());
        System.out.println("Relório 2: " + relogio2.getHorario());
        System.out.println("Diferença entre o relógio 1 e o relógio 2: " + relogio2.diferenca(relogio1) + " segundos");
        System.out.println("\n");

        // 5. Produto -----------------------------------------------------------
        System.out.println("5. Produto -------------------------------------");
        // Laboratório 1
        Produto geladeira = new Produto("Geladeira", 832);
        Produto microondas = new Produto("Micro-ondas", 499);
        geladeira.setDesconto(6);
        microondas.setDesconto(12);

        float geladeiraComDesconto = (((float) (100 - geladeira.getDesconto()) / 100) * geladeira.getPreco());
        float microondasComDesconto = (((float) (100 - microondas.getDesconto()) / 100) * microondas.getPreco());

        System.out.println(geladeira.getNome() + ": " + geladeiraComDesconto);
        System.out.println(microondas.getNome() + ": " + microondasComDesconto);

        System.out.println(geladeira.anuncio());
        System.out.println(microondas.anuncio());

        // Laboratório 2
        Produto fogao = new Produto("Fogão 4 bocas Eletrolux KL4003", 677);

        String[] listaDeProdutos = Produto.listaDeProdutos();

        for (int i = 0; i < listaDeProdutos.length; i++) {
            if (listaDeProdutos[i] != null) {
                System.out.println(listaDeProdutos[i]);
            }
        }

        System.out.println("\n");

        // 6. Livro -----------------------------------------------------------
        

    }
}
