/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;
import java.util.Random;

public class App {
    public static void main(String[] args) {

        // 1. Lâmpada -----------------------------------------------------------
        Lampada lampada1 = new Lampada();
        Lampada lampada2 = new Lampada();

        lampada1.ligar();
        lampada2.desligar();

        String estadoLampada1 = lampada1.verEstado() ? "ligada" : "desligada";
        String estadoLampada2 = lampada2.verEstado() ? "ligada" : "desligada";

        System.out.println("Lampada 1: " + estadoLampada1);
        System.out.println("Lampada 2: " + estadoLampada2);

        // 2. Pessoa -----------------------------------------------------------
        Pessoa p1 = new Pessoa();
        Pessoa p2 = new Pessoa();

        p1.setNome("Alice");
        p1.setIdade(22);
        p2.setNome("Bruno");
        p2.setIdade(25);

        p2.felizAniversario();
        p2.felizAniversario();
        p2.felizAniversario();

        p1.setIdade(-44);
        p2.setNome("");

        System.out.println(p1.getNome() + " tem " + p1.getIdade() + " anos.");
        System.out.println(p2.getNome() + " tem " + p2.getIdade() + " anos.");

        // 3. Retângulo -----------------------------------------------------------
        Retangulo retangulo1 = new Retangulo();
        retangulo1.setLargura(5);
        retangulo1.setAltura(4);
        System.out.println(retangulo1.getArea());
        System.out.println(retangulo1.getPerimetro());

        Retangulo[] retangulos = new Retangulo[10];
        Random r = new Random();
        float maior = 0;

        for (int i = 0; i < 10; i++) {
            retangulos[i] = new Retangulo();
            retangulos[i].setLargura(r.nextInt(1,20));
            retangulos[i].setAltura(r.nextInt(1, 20));
            if (retangulos[i].getArea() > maior) {
                maior = retangulos[i].getArea();
            }
        }

        System.out.println("A maior área é " + maior);

        // 4. Relógio -----------------------------------------------------------
        Relogio relogio = new Relogio();
        relogio.ajustarHora((byte) 14, (byte) 58, (byte) 32);
        relogio.avancaMinuto();
        relogio.avancaMinuto();
        System.out.println(relogio.getHora());
        relogio.ajustarHora((byte) 23, (byte) 59, (byte) 59);
        relogio.avancaSegundo();
        System.out.println(relogio.getHora());
        relogio.setAmpm(true);
        relogio.ajustarHora((byte) 23, (byte) 30, (byte) 45);
        System.out.println(relogio.getHora());
    }
}
